### PR TITLE
Trigger comments as versions

### PR DESCRIPTION
**Pull request by miromode**
Bot interface for triggering retries of builds using keyword phrases in PR comments.

### CODE REVIEW

**Comment by miromode** [comment]
test this please

**Comment by miromode** [comment]
test this please, concourse

**Comment by miromode** [comment]
concourse, test this please

**Comment by miromode** [comment]
build this please concourse

**Comment by miromode** [comment]
retest this please

**Comment by jtarchie** [comment]
test this, please

**Comment by jtarchie** [comment]
test this please

previous build ID is 730

**Comment by jtarchie** [comment]
For the functionality you are trying to recreate please see this [issue](https://github.com/jtarchie/pullrequest-resource/issues/46).

I will not accept a PR for this feature. Sorry.

**Comment by miromode** [comment]
@jtarchie yes i know, it's that concourse feature request being pushed to the backlog for months that's the reason I had to write this. Also I never submitted a PR back upstream, this feature is for our own use.

**Pull request merged**
